// Code generated by Slice Machine. DO NOT EDIT.

import AboutUs from './AboutUs/index.svelte';
import Brands from './Brands/index.svelte';
import Footer from './Footer/index.svelte';
import Hero from './Hero/index.svelte';
import HomeMap from './HomeMap/index.svelte';
import Image from './Image/index.svelte';
import ImageCards from './ImageCards/index.svelte';
import Projects from './Projects/index.svelte';
import Quote from './Quote/index.svelte';
import Services from './Services/index.svelte';
import Testimonials from './Testimonials/index.svelte';
import Text from './Text/index.svelte';
import TextWithImage from './TextWithImage/index.svelte';

export const components = {
	about_us: AboutUs,
	brands: Brands,
	footer: Footer,
	hero: Hero,
	home_map: HomeMap,
	image: Image,
	image_cards: ImageCards,
	projects: Projects,
	quote: Quote,
	services: Services,
	testimonials: Testimonials,
	text: Text,
	text_with_image: TextWithImage
};
